import React, { useEffect, useState } from "react";
import { ArrowLeft, Camera, Download, RefreshCw, Save, Share2, ShieldCheck, Trash2, Truck as TruckIcon, UserPlus, X } from "lucide-react";
import { jsPDF } from "jspdf";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import { supabase } from "@/lib/supabase";
import { type FleetRole, useFleetAuth } from "@/contexts/FleetAuthContext";
import Login from "@/pages/Login";

type AdminTruck = { id: string; fleet_number: string; registration: string; truck_type: string | null; model: string | null; size: string | null; status: "ready" | "inspection_due" | "out_of_service" };
type AdminDriver = { id: string; auth_user_id: string | null; employee_number: string | null; full_name: string; phone: string | null; role: FleetRole; active: boolean };
type ReportRow = { id: string; inspection_date: string; started_at: string | null; submitted_at: string | null; status: string; notes: string | null; driver: { full_name: string; employee_number: string | null } | null; truck: { fleet_number: string; registration: string; model: string | null } | null; answers: { result: string; checklist_item: { label: string } | null }[]; photos: { id: string; photo_type: string; storage_path: string; captured_at: string }[] };
type GalleryPhoto = { id: string; photo_type: string; storage_path: string; captured_at: string; truck: string; driver: string; url?: string };

export function AdminGate({ children }: { children: React.ReactNode }) {
  const { loading, profile, signOut } = useFleetAuth();
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#ede9dd] text-[#2e4335]">Loading secure admin area…</div>;
  if (!profile) return <Login mode="admin" onSuccess={() => window.location.reload()} />;
  if (profile.role !== "admin") return <main className="grid min-h-screen place-items-center bg-[#ede9dd] p-6"><div className="max-w-md rounded-2xl border border-[#e1c4b7] bg-[#fff5f0] p-8 text-center"><ShieldCheck className="mx-auto h-10 w-10 text-[#b65323]" /><h1 className="mt-4 font-slab text-3xl font-bold text-[#2e4335]">Management access required</h1><p className="mt-3 text-sm leading-6 text-[#6d7a6d]">This page is restricted to the admin role.</p><Button type="button" variant="outline" onClick={() => { void signOut().finally(() => window.location.replace(import.meta.env.BASE_URL)); }} className="mt-6 h-10 rounded-lg bg-[#fbf8ef] text-xs font-bold"><ArrowLeft className="mr-2 h-3.5 w-3.5" />Back to sign in</Button></div></main>;
  return <>{children}</>;
}
export default function Admin() { return <AdminGate><AdminWorkspace /></AdminGate>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-bold uppercase tracking-[0.12em] text-[#667466]">{label}<div className="mt-2">{children}</div></label>; }
function toastSuccess(message: string) { window.dispatchEvent(new CustomEvent("field-ledger-toast", { detail: { type: "success", message } })); }
function toastError(message: string) { window.dispatchEvent(new CustomEvent("field-ledger-toast", { detail: { type: "error", message } })); }

function AdminWorkspace() {
  const { profile, signOut } = useFleetAuth();
  const [trucks, setTrucks] = useState<AdminTruck[]>([]); const [drivers, setDrivers] = useState<AdminDriver[]>([]); const [reports, setReports] = useState<ReportRow[]>([]); const [gallery, setGallery] = useState<GalleryPhoto[]>([]); const [loading, setLoading] = useState(true);
  const [truckForm, setTruckForm] = useState({ fleet_number: "", registration: "", truck_type: "", model: "", size: "", status: "ready" as AdminTruck["status"] }); const [driverForm, setDriverForm] = useState({ auth_user_id: "", employee_number: "", full_name: "", phone: "", role: "driver" as FleetRole });
  const [editingTruckId, setEditingTruckId] = useState<string | null>(null); const [openCard, setOpenCard] = useState<"driver" | "truck" | null>(null); const [reportDate, setReportDate] = useState(() => new Date().toISOString().slice(0, 10)); const [selectedPhoto, setSelectedPhoto] = useState<GalleryPhoto | null>(null);

  const load = async () => {
    if (!supabase) { setLoading(false); return; } const client = supabase; setLoading(true);
    const [{ data: truckData, error: truckError }, { data: driverData, error: driverError }, { data: reportData, error: reportError }] = await Promise.all([
      supabase.from("trucks").select("id, fleet_number, registration, truck_type, model, size, status").order("fleet_number"),
      supabase.from("drivers").select("id, auth_user_id, employee_number, full_name, phone, role, active").order("full_name"),
      supabase.from("daily_inspections").select("id, inspection_date, started_at, submitted_at, status, notes, driver:drivers(full_name, employee_number), truck:trucks(fleet_number, registration, model), answers:inspection_answers(result, checklist_item:checklist_items(label)), photos:inspection_photos(id, photo_type, storage_path, captured_at)").eq("inspection_date", reportDate).order("created_at", { ascending: false }),
    ]);
    if (truckError || driverError || reportError) toastError((truckError || driverError || reportError)?.message || "Unable to load admin data.");
    setTrucks((truckData ?? []) as AdminTruck[]); setDrivers((driverData ?? []) as AdminDriver[]); const rows = (reportData ?? []) as unknown as ReportRow[]; setReports(rows);
    const photoRows = rows.flatMap((row) => (row.photos ?? []).map((photo) => ({ ...photo, truck: row.truck?.fleet_number || "Unknown truck", driver: row.driver?.full_name || "Unknown driver" })));
    const signed = await Promise.all(photoRows.map(async (photo) => { const result = await client.storage.from("inspection-photos").createSignedUrl(photo.storage_path, 3600); return { ...photo, url: result.data?.signedUrl }; })); setGallery(signed); setLoading(false);
  };
  useEffect(() => { void load(); }, [reportDate]);

  const saveTruck = async (event: React.FormEvent) => { event.preventDefault(); if (!supabase) return; const payload = { fleet_number: truckForm.fleet_number.trim(), registration: truckForm.registration.trim().toUpperCase(), truck_type: truckForm.truck_type.trim() || null, model: truckForm.model.trim() || null, size: truckForm.size.trim() || null, status: truckForm.status }; if (!payload.fleet_number || !payload.registration) return toastError("Fleet number and registration are required."); const result = editingTruckId ? await supabase.from("trucks").update(payload).eq("id", editingTruckId) : await supabase.from("trucks").insert(payload); if (result.error) return toastError(result.error.message); toastSuccess(editingTruckId ? "Truck updated." : "Truck added."); setTruckForm({ fleet_number: "", registration: "", truck_type: "", model: "", size: "", status: "ready" }); setEditingTruckId(null); setOpenCard(null); await load(); };
  const saveDriver = async (event: React.FormEvent) => { event.preventDefault(); if (!supabase) return; const payload = { auth_user_id: driverForm.auth_user_id.trim() || null, employee_number: driverForm.employee_number.trim() || null, full_name: driverForm.full_name.trim(), phone: driverForm.phone.trim() || null, role: driverForm.role, active: true }; if (!payload.full_name) return toastError("Driver name is required."); const { error } = await supabase.from("drivers").insert(payload); if (error) return toastError(error.message); toastSuccess("Driver profile added."); setDriverForm({ auth_user_id: "", employee_number: "", full_name: "", phone: "", role: "driver" }); setOpenCard(null); await load(); };
  const deleteTruck = async (truck: AdminTruck) => { if (!supabase || !window.confirm(`Delete fleet ${truck.fleet_number}? This cannot be undone.`)) return; const { error } = await supabase.from("trucks").delete().eq("id", truck.id); if (error) return toastError(error.message); toastSuccess("Truck deleted."); await load(); };
  const deleteDriver = async (driver: AdminDriver) => { if (!supabase || !window.confirm(`Delete ${driver.full_name}'s fleet profile?`)) return; const { error } = await supabase.from("drivers").delete().eq("id", driver.id); if (error) return toastError(error.message); toastSuccess("Driver profile deleted."); await load(); };
  const exportFleet = () => { const rows = [["Fleet number", "Registration", "Truck type", "Model", "Size", "Status"], ...trucks.map((t) => [t.fleet_number, t.registration, t.truck_type ?? "", t.model ?? "", t.size ?? "", t.status])]; const csv = rows.map((row) => row.map((v) => `"${String(v).replaceAll('"', '""')}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = `field-ledger-fleet-${reportDate}.csv`; link.click(); };
  const shareReport = async () => { const pdf = new jsPDF(); pdf.setFontSize(18); pdf.text("Field Ledger — Fleet Inspection Report", 16, 20); pdf.setFontSize(10); pdf.text(`Report date: ${reportDate}`, 16, 28); pdf.text(`Inspections: ${reports.length} | Evidence photos: ${gallery.length}`, 16, 36); let y = 48; reports.forEach((row) => { pdf.text(`${row.truck?.fleet_number || "Unknown truck"} · ${row.driver?.full_name || "Unknown driver"}`, 16, y); pdf.text(`${row.status.replaceAll("_", " ")} · ${row.submitted_at ? new Date(row.submitted_at).toLocaleString() : "Not submitted"} · ${row.photos?.length || 0}/6 photos`, 16, y + 6); y += 14; if (y > 275) { pdf.addPage(); y = 20; } }); const blob = pdf.output("blob"); const file = new File([blob], `field-ledger-report-${reportDate}.pdf`, { type: "application/pdf" }); if (navigator.share && navigator.canShare?.({ files: [file] })) await navigator.share({ title: "Field Ledger inspection report", text: `Fleet inspection report for ${reportDate}`, files: [file] }); else { const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = file.name; link.click(); toastSuccess("Report PDF downloaded."); } };
  const startEdit = (truck: AdminTruck) => { setEditingTruckId(truck.id); setTruckForm({ fleet_number: truck.fleet_number, registration: truck.registration, truck_type: truck.truck_type ?? "", model: truck.model ?? "", size: truck.size ?? "", status: truck.status }); setOpenCard("truck"); };

  return <main className="min-h-screen bg-[#ede9dd] text-[#2e4335]"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-[#d8d3c5] bg-[#f7f3e9] px-4 py-4 sm:px-8"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#2f4638] text-[#f4a36f]"><ShieldCheck className="h-5 w-5" /></div><div><p className="font-slab text-xl font-bold">Admin control</p><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#7b8775]">Field Ledger · {profile?.full_name}</p></div></div><div className="flex items-center gap-2"><Button variant="outline" onClick={exportFleet} className="h-9 rounded-lg bg-[#fbf8ef] text-xs font-bold"><Download className="mr-2 h-3.5 w-3.5" />Export fleet</Button><Button variant="outline" onClick={() => void load()} className="h-9 rounded-lg bg-[#fbf8ef] text-xs font-bold"><RefreshCw className="mr-2 h-3.5 w-3.5" />Refresh</Button><Button variant="outline" onClick={() => void signOut()} className="h-9 rounded-lg bg-[#fbf8ef] text-xs font-bold"><X className="mr-2 h-3.5 w-3.5" />Sign out</Button></div></header><div className="mx-auto max-w-7xl space-y-6 p-4 pb-16 sm:p-8"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-[#7c887b]"><button type="button" onClick={() => { void signOut().finally(() => window.location.replace(import.meta.env.BASE_URL)); }} className="inline-flex items-center gap-2 hover:text-[#e9682a]"><ArrowLeft className="h-3.5 w-3.5" />Return to workspace</button><span>/</span><span className="text-[#e9682a]">Admin only</span></div>
<section className="grid gap-3 md:grid-cols-2"><ActionCard icon={UserPlus} title="Add driver" detail={`${drivers.length} profiles in roster`} open={openCard === "driver"} onClick={() => setOpenCard(openCard === "driver" ? null : "driver")} /><ActionCard icon={TruckIcon} title={editingTruckId ? "Edit truck" : "Add truck"} detail={`${trucks.length} fleet records`} open={openCard === "truck"} onClick={() => setOpenCard(openCard === "truck" ? null : "truck")} /></section>
{openCard === "driver" && <form onSubmit={saveDriver} className="paper-panel rounded-2xl border border-[#d8d3c5] p-5"><div className="mb-5 flex items-center justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#6a7769]">Roster control</p><h2 className="font-slab text-2xl font-bold">Add driver profile</h2></div><Button type="button" variant="ghost" onClick={() => setOpenCard(null)}><X className="h-4 w-4" /></Button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Auth user UID"><Input value={driverForm.auth_user_id} onChange={(e) => setDriverForm({ ...driverForm, auth_user_id: e.target.value })} /></Field><Field label="Full name"><Input required value={driverForm.full_name} onChange={(e) => setDriverForm({ ...driverForm, full_name: e.target.value })} /></Field><Field label="Employee number"><Input value={driverForm.employee_number} onChange={(e) => setDriverForm({ ...driverForm, employee_number: e.target.value })} /></Field><Field label="Phone"><Input value={driverForm.phone} onChange={(e) => setDriverForm({ ...driverForm, phone: e.target.value })} /></Field><Field label="Role"><select value={driverForm.role} onChange={(e) => setDriverForm({ ...driverForm, role: e.target.value as FleetRole })} className="h-10 w-full rounded-xl border border-[#d4cfc1] bg-[#fffdf6] px-3 text-sm"><option value="driver">Driver</option><option value="admin">Admin</option></select></Field></div><Button type="submit" className="mt-5 h-11 w-full rounded-xl bg-[#e9682a] text-sm font-bold text-white"><UserPlus className="mr-2 h-4 w-4" />Add profile</Button></form>}
{openCard === "truck" && <form onSubmit={saveTruck} className="paper-panel rounded-2xl border border-[#d8d3c5] p-5"><div className="mb-5 flex items-center justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#6a7769]">Fleet control</p><h2 className="font-slab text-2xl font-bold">{editingTruckId ? "Edit truck" : "Add truck"}</h2></div><Button type="button" variant="ghost" onClick={() => { setOpenCard(null); setEditingTruckId(null); }}><X className="h-4 w-4" /></Button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Fleet number"><Input required value={truckForm.fleet_number} onChange={(e) => setTruckForm({ ...truckForm, fleet_number: e.target.value })} /></Field><Field label="Registration"><Input required value={truckForm.registration} onChange={(e) => setTruckForm({ ...truckForm, registration: e.target.value })} /></Field><Field label="Truck type"><Input value={truckForm.truck_type} onChange={(e) => setTruckForm({ ...truckForm, truck_type: e.target.value })} /></Field><Field label="Model"><Input value={truckForm.model} onChange={(e) => setTruckForm({ ...truckForm, model: e.target.value })} /></Field><Field label="Size"><Input value={truckForm.size} onChange={(e) => setTruckForm({ ...truckForm, size: e.target.value })} /></Field><Field label="Status"><select value={truckForm.status} onChange={(e) => setTruckForm({ ...truckForm, status: e.target.value as AdminTruck["status"] })} className="h-10 w-full rounded-xl border border-[#d4cfc1] bg-[#fffdf6] px-3 text-sm"><option value="ready">Ready</option><option value="inspection_due">Inspection due</option><option value="out_of_service">Out of service</option></select></Field></div><Button type="submit" className="mt-5 h-11 w-full rounded-xl bg-[#2f4638] text-sm font-bold text-white"><Save className="mr-2 h-4 w-4" />{editingTruckId ? "Save truck" : "Add truck"}</Button></form>}

<section className="paper-panel overflow-hidden rounded-2xl border border-[#d8d3c5]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#dfd9ca] px-5 py-5"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#6a7769]">Manager report</p><h2 className="font-slab text-2xl font-bold">Complete inspection report</h2><p className="mt-1 text-xs text-[#718070]">Checklist outcomes, driver, truck, timestamps, notes, and evidence completeness.</p></div><div className="flex gap-2"><Input type="date" value={reportDate} onChange={(e) => setReportDate(e.target.value)} className="h-9 w-[145px]" /><Button onClick={() => void shareReport()} className="h-9 bg-[#e9682a] text-xs font-bold text-white"><Share2 className="mr-2 h-3.5 w-3.5" />Share PDF</Button></div></div><div className="divide-y divide-[#e5dfd3]">{loading ? <div className="p-6 text-sm">Loading report…</div> : reports.length === 0 ? <div className="p-6 text-sm text-[#7c887b]">No inspections recorded for {reportDate}.</div> : reports.map((row) => <div key={row.id} className="px-5 py-4"><div className="flex flex-wrap items-center gap-3"><span className="font-mono text-sm font-bold">{row.truck?.fleet_number || "Unknown truck"}</span><span className="text-sm font-semibold">{row.driver?.full_name || "Unknown driver"}</span><span className="text-xs text-[#718070]">{row.submitted_at ? new Date(row.submitted_at).toLocaleString() : "Not submitted"}</span><span className="ml-auto rounded-full bg-[#e8eee5] px-2.5 py-1 text-[10px] font-bold uppercase">{row.status.replaceAll("_", " ")}</span></div><div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-xs text-[#718070]"><span>{row.answers?.filter((a) => a.result === "pass").length || 0} passed · {row.answers?.filter((a) => a.result === "fail").length || 0} failed</span><span className={cn(row.photos?.length === 6 ? "text-[#2f8b5e]" : "text-[#b65323]", "font-bold")}>{row.photos?.length || 0}/6 evidence photos</span>{row.notes && <span className="truncate">Note: {row.notes}</span>}</div></div>)}</div></section>
<section className="paper-panel overflow-hidden rounded-2xl border border-[#d8d3c5]"><div className="border-b border-[#dfd9ca] px-5 py-5"><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#6a7769]">Evidence library</p><h2 className="font-slab text-2xl font-bold">Truck inspection photos</h2></div><div className="grid grid-cols-2 gap-3 p-5 sm:grid-cols-3 lg:grid-cols-6">{gallery.length === 0 ? <p className="col-span-full text-sm text-[#7c887b]">No captured evidence photos for this date.</p> : gallery.map((photo) => <button key={photo.id} type="button" onClick={() => setSelectedPhoto(photo)} className="group overflow-hidden rounded-xl border border-[#d8d3c5] bg-[#f5f1e7] text-left"><div className="aspect-square bg-[#e5e1d5]">{photo.url ? <img src={photo.url} alt={`${photo.truck} ${photo.photo_type}`} className="h-full w-full object-cover transition group-hover:scale-105" /> : <div className="grid h-full place-items-center"><Camera className="h-5 w-5 text-[#889286]" /></div>}</div><div className="p-2"><div className="truncate text-[10px] font-bold">{photo.truck}</div><div className="truncate text-[10px] text-[#718070]">{photo.photo_type} · {photo.driver}</div></div></button>)}</div></section><section className="paper-panel overflow-hidden rounded-2xl border border-[#d8d3c5]"><div className="flex items-center justify-between border-b border-[#dfd9ca] px-5 py-5"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#6a7769]">Master fleet</p><h2 className="font-slab text-2xl font-bold">Fleet records</h2></div><span className="rounded-full bg-[#e8eee5] px-3 py-1 text-xs font-bold">{trucks.length} trucks</span></div><div className="divide-y divide-[#e5dfd3]">{loading ? <div className="p-6 text-sm">Loading fleet records…</div> : trucks.map((truck) => <div key={truck.id} role="button" tabIndex={0} onClick={() => startEdit(truck)} onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") startEdit(truck); }} className="flex cursor-pointer flex-wrap items-center gap-3 px-5 py-4 hover:bg-[#f5f1e7]"><div className="grid h-9 w-9 place-items-center rounded-lg bg-[#e8eee5]"><TruckIcon className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="font-mono text-sm font-bold">{truck.fleet_number}</div><div className="font-mono text-xs font-bold text-[#e9682a]">{truck.registration}</div></div><span className="text-xs font-semibold">{truck.status.replaceAll("_", " ")}</span><Button variant="outline" onClick={(e) => { e.stopPropagation(); startEdit(truck); }} className="h-8 text-xs font-bold">Edit</Button><Button variant="outline" onClick={(e) => { e.stopPropagation(); void deleteTruck(truck); }} className="h-8 text-xs text-[#a44b2d]"><Trash2 className="h-3.5 w-3.5" /></Button></div>)}</div></section>
{selectedPhoto && <div className="fixed inset-0 z-50 grid place-items-center bg-[#1f3529]/75 p-4" onClick={() => setSelectedPhoto(null)}><div className="max-h-[90vh] max-w-3xl overflow-hidden rounded-2xl bg-[#fbf8ef] shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between p-3"><div className="text-xs font-bold">{selectedPhoto.truck} · {selectedPhoto.photo_type}</div><Button variant="ghost" onClick={() => setSelectedPhoto(null)}><X className="h-4 w-4" /></Button></div>{selectedPhoto.url && <img src={selectedPhoto.url} alt="Inspection evidence" className="max-h-[78vh] w-full object-contain" />}<div className="px-4 py-3 text-xs text-[#718070]">Captured by {selectedPhoto.driver} on {new Date(selectedPhoto.captured_at).toLocaleString()}</div></div></div>}
<section className="paper-panel overflow-hidden rounded-2xl border border-[#d8d3c5]"><div className="flex items-center justify-between border-b border-[#dfd9ca] px-5 py-5"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#6a7769]">People</p><h2 className="font-slab text-2xl font-bold">Driver profiles</h2></div><span className="text-xs font-bold">{drivers.length} profiles</span></div><div className="divide-y divide-[#e5dfd3]">{drivers.map((driver) => <div key={driver.id} className="flex items-center gap-3 px-5 py-4"><div className="grid h-9 w-9 place-items-center rounded-full bg-[#e9eee7] text-xs font-bold">{driver.full_name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-bold">{driver.full_name}</div><div className="text-xs text-[#849083]">{driver.role} · {driver.employee_number || "No employee number"}</div></div><Button variant="outline" onClick={() => void deleteDriver(driver)} className="h-8 text-xs text-[#a44b2d]"><Trash2 className="h-3.5 w-3.5" /></Button></div>)}</div></section></div></main>;
}
function ActionCard({ icon: Icon, title, detail, open, onClick }: { icon: React.ElementType; title: string; detail: string; open: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={cn("paper-panel flex items-center gap-4 rounded-2xl border border-[#d8d3c5] p-5 text-left transition hover:border-[#e9682a]", open && "border-[#e9682a] bg-[#fff6eb]")}><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#e8eee5] text-[#45664e]"><Icon className="h-5 w-5" /></span><span className="min-w-0 flex-1"><span className="block font-slab text-xl font-bold">{title}</span><span className="text-xs text-[#718070]">{detail}</span></span><span className="text-xs font-bold uppercase tracking-[0.12em] text-[#e9682a]">{open ? "Close" : "Open"}</span></button>; }
